<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\CurrentProduct;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

?>
<?php
$currentProductModel = $viewModels->require(CurrentProduct::class, $block);
$product = $currentProductModel->get();
?>

<div id="real-qty-block" data-product-sku="<?= $escaper->escapeHtml($product->getSku())?>" class="hidden">
    <span class="real-qty">
        <?= $escaper->escapeHtml(__('Available Qty'))?>:
        <span id="real-qty-value"></span>
    </span>
</div>

<script>
    "use strict";
    function initProductQtyUpdating(event) {
        const sectionData = event.detail.data;
        const sku = document.querySelector('#real-qty-block').getAttribute('data-product-sku');
        const formKey = hyva.getFormKey();

        setInterval(function(){
            fetch(`${BASE_URL}product/qty/update/`, {
                method: 'post',
                body: new URLSearchParams(
                    {
                        sku: sku,
                        form_key: formKey
                    }
                ),
                headers: {
                    'contentType': 'application/json',
                    'accept': 'application/json'
                }
            })
                .then(response => {
                    if (! response.ok) console.warn('GET request failed');
                    return response.json()
                })
                .then(data => {
                    if (data.error == false) {
                        let qty = data.product_qty;
                        document.querySelector('#real-qty-value').innerText = qty;
                        document.querySelector('#real-qty-block').style.display = 'block';
                    } else {
                        console.log('Error: ' + data.message);
                    }
                });
        }, 5000);
    }

    window.addEventListener("private-content-loaded", initProductQtyUpdating);
</script>
